import Link from 'next/link';
import React from 'react';

export function Logo(){return <Link href="/" className="brand" aria-label="NovaClear home"><img src="/novaclear-logo.jpg" alt="NovaClear - A Fresh Start. A Better Future." style={{height:72,width:'auto',display:'block'}}/></Link>}

export function Header(){return <><div className="topbar"><div className="container"><a href="tel:+27210026137">Landline: +27 21 002 6137</a><a href="https://wa.me/27796727637" target="_blank">WhatsApp: 079 672 7637</a></div></div><header className="site-header"><div className="container nav-wrap"><Logo/><nav className="nav"><Link href="/about">Who we are</Link><Link href="/debt-review">Debt review</Link><Link href="/debt-consolidation">Debt consolidation</Link><Link href="/credit-monitoring">Credit health</Link><Link href="/faq">FAQs</Link><Link href="/contact">Contact</Link><Link className="cta" href="/contact">Call me back</Link></nav><Link className="btn btn-primary mobile-only" href="/contact">Get help</Link></div></header></>}

export function Footer(){return <><div className="contact-strip"><div className="container"><strong>Ready for a fresh financial start?</strong><Link href="/contact" className="btn">Request a call back</Link></div></div><footer><div className="container"><div className="footer-grid"><div><Logo/><p style={{color:'#b9cad3',lineHeight:1.7,maxWidth:350}}>NovaClear helps South Africans understand their debt options and take practical steps toward a more manageable financial future.</p></div><div><div className="footer-title">Solutions</div><div className="footer-links"><Link href="/debt-review">Debt review</Link><Link href="/debt-consolidation">Debt consolidation</Link><Link href="/credit-monitoring">Credit health</Link></div></div><div><div className="footer-title">NovaClear</div><div className="footer-links"><Link href="/about">About us</Link><Link href="/faq">FAQs</Link><Link href="/contact">Contact</Link></div></div><div><div className="footer-title">Contact</div><div className="footer-links"><a href="tel:+27210026137">+27 21 002 6137</a><a href="https://wa.me/27796727637">079 672 7637</a><span>5 Beverly Road, Athlone</span></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} NovaClear. All rights reserved.</span><span>Information on this website is general and does not constitute legal or financial advice.</span></div></div></footer><a className="whatsapp" href="https://wa.me/27796727637?text=Hi%20NovaClear%2C%20I%20would%20like%20help%20with%20my%20debt." target="_blank" aria-label="Chat on WhatsApp">✆</a></>}

export function LeadForm(){return <div className="form-card"><h3>Let us call you back</h3><p>Tell us how to reach you and a NovaClear consultant can contact you.</p><form className="form-grid" action="mailto:" method="post"><div className="field"><label>First name</label><input name="name" required placeholder="Your name"/></div><div className="field"><label>Surname</label><input name="surname" required placeholder="Your surname"/></div><div className="field"><label>Phone number</label><input name="phone" required placeholder="e.g. 079 123 4567"/></div><div className="field"><label>Email</label><input name="email" type="email" placeholder="name@example.co.za"/></div><div className="field full"><label>What do you need help with?</label><select name="service"><option>Debt review</option><option>Debt consolidation guidance</option><option>Credit health</option><option>General enquiry</option></select></div><div className="field full"><button className="btn btn-primary" type="submit">Request my call back</button><p className="form-note">By submitting, you agree that NovaClear may contact you about your enquiry.</p></div></form></div>}

export function PageHero({eyebrow,title,children}:{eyebrow:string,title:string,children:React.ReactNode}){return <section className="page-hero"><div className="container"><div className="eyebrow" style={{color:'#8ce58e'}}>{eyebrow}</div><h1>{title}</h1><p>{children}</p></div></section>}
